### ISSUE TITLE
fix issue in `SwitchSrcDstPorts()` function

### ISSUE THREAD

**Issue by adisos** [np-guard/vpc-network-config-analyzer#170]
handle ICMP protocol as well 

currently test output `pkg/ibmvpc/examples/acl_testing5subnetsBased_withPGW.txt` is affected by this issue

**Comment by adisos** [comment]
Check if icmp type and code is identical in the response direction

**Comment by ShiriMoran** [comment]
`src` and `dst` ports are not relevant for an `ICMP` connection.
If indeed in an `ICMP` the response type and code are identical to these in the original direction, then in order to check if an `ICMP` connection is stateful, switching ports directions as in `SwitchSrcDstPorts()` is not needed. It suffice to verify that an identical connection exists in the other direction.
