### ISSUE TITLE
analyzer failing to unmarshal config object

### ISSUE THREAD

**Issue by kyorav** [np-guard/vpc-network-config-analyzer#342]
The attached config object was created using the latest version of the collector (built from the main branch), invoked like this:
```
../../cloud-resource-collector/bin/collect -provider ibm -out tmp.json -region us-south
```

I ran the latest version of the analyzer (built from main branch) on an anonymized version of the result
```
$ ../../vpc-network-config-analyzer/bin/vpcanalyzer -vpc-config config_object.json -analysis-type all_subnets -format txt --output-file all_subnets_analysis.txt
2024/01/24 16:40:59 error parsing input vpc resources file: json: cannot unmarshal object into Go struct field Vpcdns.vpcs.dns.resolver of type vpcv1.VpcdnsResolverIntf. exiting...
```
[config_object.json](https://github.com/np-guard/vpc-network-config-analyzer/files/14039848/config_object.json)

**Comment by zivnevo** [comment]
This is expected. Analyzer only consumes official releases of the collector. You should use version 0.4.0 of the collector (there is a tag for that)

**Comment by kyorav** [comment]
I ran again with v0.4.0 of the collector, and both v0.2.1 and main of the analyzer. Similar problem different messages:
```
2024/01/24 17:09:41 error parsing input vpc resources file: json: cannot unmarshal string into Go value of type []json.RawMessage. exiting...
```
```
2024/01/24 17:47:19 error parsing input vpc resources file: json: cannot unmarshal object into Go struct field Vpcdns.vpcs.dns.resolver of type vpcv1.VpcdnsResolverIntf. exiting...
```
Attaching the new config_object (collected by v0.4.0, more VPCs because I continued to work in the meantime).
[config_object.json](https://github.com/np-guard/vpc-network-config-analyzer/files/14040200/config_object.json)

**Comment by zivnevo** [comment]
@olasaadi99 , can you please take a look? Are we missing an `Unmarshal` function in the collector?

**Comment by adisos** [comment]
This seems related to another type that is now collected and has a field of type interface, thus requiring us to add in the collector yet another wrapper type (see from the error: `field Vpcdns.vpcs.dns.resolver of type vpcv1.VpcdnsResolverIntf`).
This should be similar to the fix that @olasaadi99  has added previously for one of the fields of routing table. 

There is also an open an issue to fix/improve the unmarshaling approach (relevant issue: https://github.com/np-guard/cloud-resource-collector/issues/175), so that we don't have to keep facing broken unmarshal functionality due to new collected objects with fields of type interface.

**Comment by olasaadi99** [comment]
pr https://github.com/np-guard/cloud-resource-collector/pull/181

**Comment by adisos** [comment]
The issue was fixed in the collector, waiting for new collector version to be released.
