### ISSUE TITLE
explainability for html

### ISSUE THREAD

**Issue by haim-kermany** [np-guard/vpc-network-config-analyzer#370]
In general, for html, we need explanation for each pair elements in the canvas
(an element can be a node, subnet, group ...)
however, Shiri mention that explainability query be more specific (by protocol, specific cidr, ...)

**Comment by adisos** [comment]
I assume that for html, explainability is relevant for 2 endpoints and the connection on the edge (for connected endpoints), and for non-connected endpoints - explanation why there is no connection. 
The html is indeed not intuitive for the use case where some connection exists between 2 endpoints, but the user wants to figure out why there is no connection on certain protocol/port (rather than explanation on the existing different connection)

**Comment by haim-kermany** [comment]
@ShiriMoran @adisos 
is there a plane to generate explainability for every pair of  endpoints in one analyzer run?

**Comment by adisos** [comment]
> @ShiriMoran @adisos is there a plane to generate explainability for every pair of endpoints in one analyzer run?

I think we should open an issue for that, if it is required for this item.

**Comment by ShiriMoran** [comment]
resolved by #536
