### ISSUE TITLE
Allow the user to use the `-region` and `-resource-group` flags to also filter resources that we got from `-vpc-config`

### ISSUE THREAD

**Issue by olasaadi99** [np-guard/vpc-network-config-analyzer#407]

**Comment by zivnevo** [comment]
Filtering by region is a bit more tricky than filtering by resource group, because it's only VPCs that carry the region field. I suggest the following:
* Filtering by resource group can be done right after unmarshalling the config, and before calling the parser.
* Filtering by region should be applied later on in the process, while the parser builds a VPCConfig for each VPC. We can then skip creating VPCConfigs for VPCs in regions not specified by the user. A special care should be taken when creating multi-cloud VPCConfig (for transit gateways). @adisos can advise.

This is somewhat related to Issue #264.
