### ISSUE TITLE
Explainability: support in multi vpc wo supporting tgw

### ISSUE THREAD

**Issue by ShiriMoran** [np-guard/vpc-network-config-analyzer#454]
preliminary stage to supporting tgw as per #368

**Comment by kyorav** [comment]
Yes, we are also adding this kind of disambiguation into the synthesis because of the move to multiple vpcs. On the synthesis side we chose to use `vpc1/vsi1-ky`  since this is the best-practice for scoping in the cloud. I recommend we do the same here. 

BTW, yesterday I discovered that even within the same VPC, NIF names don't need to be unique, so you'll need things like `vpc1/vsi1-ky/eth0`.

**Comment by ShiriMoran** [comment]
I'll add it after the current PR is merged
